# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  hostname: <%= ENV.fetch('HOSTNAME', 'localhost:3000') %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>

development:
  <<: *defaults
  secret_key_base: fc10280147ee153d098675a4275356656728b8606b6c2c8e9070f6c4af3a27885d66592af99cfc71ff6b76c1734c0b5044ad2fed5d1a470a0ce5258942bfb31d

test:
  <<: *defaults
  secret_key_base: 24e44eccf7fee20de476da211c447e93244b303543b1ce33d63d0ab1df0e8312ac132dbd069531b13ef07a5fbdeef48d55708f43c143e766d071b6d08bc379db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  hostname: <%= ENV['HOSTNAME'] || (ENV['HEROKU_APP_NAME'] ? "#{ENV['HEROKU_APP_NAME']}.herokuapp.com" : nil) %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] || ENV['MAILGUN_SMTP_SERVER'] %>
  smtp_port: <%= ENV["SMTP_PORT"] || ENV['MAILGUN_SMTP_PORT'] || 587 %>
  smtp_username: <%=  ENV["SMTP_USERNAME"] || ENV['MAILGUN_SMTP_LOGIN'] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] || ENV['MAILGUN_SMTP_PASSWORD'] %>
  smtp_subaccount: <%= ENV["SMTP_SUBACCOUNT"] %>

staging:
  <<: *production
